### PR TITLE
Suite timeout option

### LINKED ISSUE #2: Add a way run only the fastest fraction of tests
## What

Add an option called something like `exitAfterFractionFinished` that accepts numbers from zero to one. It should default to one.

The option will be used to end tests early after the specified fraction of tests have ended. If they all passed, consider it a pass. If any failed, consider it a failure.

For example, if there are 10 tests, and `exitAfterFractionFinished` is `0.9`, then the tests should exit after the first 9 exit.

## How

When each test ends, check the number that have already passed and end the process if enough have passed.

The process should be ended gently enough that normal cleanup operations can still happen.

There should be logging at the end to make it really clear that not all the tests finished.

### PR DESCRIPTION
**Pull request by Tyler-Murphy**
Closes #2. This supports a time limit, rather than the fastest fraction, but it serves the same purpose of allowing just fast tests to run.

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -35,20 +54,42 @@ function test(description: Test['description'], testFunction: Test['testFunction
...
     testsRunning = true
-    await runTests()
+    await runTests(testSuiteOptions)
 
     debugLog(`(${Date.now() - startTime} ms) done running tests`)
 
     process.exitCode = errorCount > 0 ? 1 : 0
+
+    debugLog(`Sending kill signal SIGINT to self (process ID ${process.pid}). There are ${process.listenerCount(`SIGINT`)} current listeners for this signal.`)
+    process.kill(process.pid, `SIGINT`)  // exit the process, but allow handlers to catch the `SIGINT` and clean up as necessary. This is a gentler alternative to `process.exit()`.
```
Comment (Tyler-Murphy) [inline src/index.ts]: Maybe this should only happen if tests were cut off by the timeout. It could cause unexpected early exits, otherwise.

Comment (Tyler-Murphy) [reply src/index.ts]: Fixed in 05fbf11b134b58e8e2fc3909a1c0d14cd64bd1d1.

File: src/bin/test-all.ts [hunk 2]
```diff
@@ -1,10 +1,17 @@
...
 
+import * as program from 'commander'
 import glob = require('tiny-glob')
 import debugLog from '../debugLog'
 import { resolve as resolvePath } from 'path'
 
-const paths = process.argv.slice(2)
+program
+.option('--maximumDurationSeconds <maximumDurationSeconds>', 'The maximum amount of time that tests in the suite are allowed to run. Defaults to `3600`')
+.option('--path <path>', 'The path to the test file(s) to run. Can be a glob pattern to run many at once. Can be repeated', (newPath, existingPaths) => [...existingPaths, newPath], [])
```
Comment (Tyler-Murphy) [inline src/bin/test-all.ts]:
```suggestion
.option('--path <path>', 'The path to the test file(s) to run. Can be a glob pattern to run many at once. Can be repeated, e.g., --path path1 --path path2', (newPath, existingPaths) => [...existingPaths, newPath], [])
```

File: src/bin/test-all.ts [hunk 3]
```diff
@@ -25,4 +32,10 @@ Promise.all(paths.map(path => glob(path)))
       debugLog(`(${Date.now() - startTime} ms) loaded ${match}`)
     })
   })
+
```
Comment (Tyler-Murphy) [inline src/bin/test-all.ts:35]: Can we add a comment explaining all of this here:
 - index has to be loaded in the same syncronous chunk as test registry
 - If async before, it would load index and run 0 tests.
 - if async after, tests would run without the settings.

File: src/index.ts [hunk 4]
```diff
@@ -4,16 +4,36 @@ import * as getStackOnly from 'extract-stack'
...
 const tests: Array<Test> = []
+let successCount = 0
 let errorCount = 0
 let testsRunning = false
+let testsTimedOut = false
 const writeOutput = (line: string) => console.log(line)
+let testSuiteOptions: TestSuiteOptions = {
+    maximumDurationSeconds: 3600,
+}
+let testSuiteOptionsSet = false
```
Comment (Tyler-Murphy) [inline src/index.ts]:
```suggestion
let testSuiteOptionsHaveBeenSet = false
```

File: src/index.ts [hunk 5]
```diff
@@ -35,20 +55,44 @@ function test(description: Test['description'], testFunction: Test['testFunction
...
     debugLog('running tests')
 
     testsRunning = true
-    await runTests()
+    await runTests(testSuiteOptions)
 
     debugLog(`(${Date.now() - startTime} ms) done running tests`)
 
     process.exitCode = errorCount > 0 ? 1 : 0
+
```
Comment (Tyler-Murphy) [inline src/index.ts:86]:
```suggestion
// At this point, all parallel-test behavior is complete. We need to stop any tests that are still running.
```

File: src/test/multipleTestSuiteOptionSets.ts [hunk 6]
```diff
@@ -0,0 +1,4 @@
+import { setTestSuiteOptions } from '../index'
```
Comment (Tyler-Murphy) [inline src/test/multipleTestSuiteOptionSets.ts:5]:
```suggestion
This file can be used to test `setTestSuiteOptions` manually, because these things are difficult to write automated tests for.

You can run this file to see the behavior if you set test suite options multiple times, and it should throw an error.

import { setTestSuiteOptions } from '../index'
```

File: src/test/suite-timeout.ts [hunk 7]
```diff
@@ -0,0 +1,23 @@
+import test, { setTestSuiteOptions } from '../index'
```
Comment (Tyler-Murphy) [inline src/test/suite-timeout.ts:5]:
```suggestion
This file can be used as a manual test, because these things are difficult to write automated tests for.

The expected output for this file is...

import test, { setTestSuiteOptions } from '../index'
```

File: src/index.ts [hunk 8]
```diff
@@ -74,11 +119,24 @@ async function runTests(): Promise<void> {
...
+    await Promise.race([
+        Promise.all(pendingTests),
+        pendingSuiteTimeout,
+    ])
 
     writeOutput(`# tests ${tests.length}`)
-    writeOutput(`# pass ${tests.length - errorCount}`)
+    writeOutput(`# pass ${successCount}`)
     writeOutput(`# fail ${errorCount}`)
+    writeOutput(`# skipped ${tests.length - successCount - errorCount}`)
```
Comment (Tyler-Murphy) [inline src/index.ts]:
```suggestion
    writeOutput(`# unfinished ${tests.length - successCount - errorCount}`)
```

**Review by Tyler-Murphy — COMMENTED** [review]
In-person with Danny and Aaron.

File: src/bin/test-all.ts (hunk 3 above)
Comment (Tyler-Murphy) [reply src/bin/test-all.ts:35]: bf490772307dc5c197350993e0779182aeaf9efd

File: src/index.ts (hunk 4 above)
Comment (Tyler-Murphy) [reply src/index.ts]: 962efbc

File: src/index.ts (hunk 5 above)
Comment (Tyler-Murphy) [reply src/index.ts:86]: 04c7579

File: src/test/multipleTestSuiteOptionSets.ts (hunk 6 above)
Comment (Tyler-Murphy) [reply src/test/multipleTestSuiteOptionSets.ts:5]: 2b17ba1

File: src/test/suite-timeout.ts (hunk 7 above)
Comment (Tyler-Murphy) [reply src/test/suite-timeout.ts:5]: 2b17ba1

File: src/index.ts (hunk 8 above)
Comment (Tyler-Murphy) [reply src/index.ts]: 04c4990
